---
version: "1"
services:
  endure:
    image: ndhuynh/endure
    container_name: endure
    user: "${UID}:${GID}"
    environment:
      - TZ=America/New_York
    tty: true
    stdin_open: true

    volumes:
      - /scratchNVM1/ndhuynh/data:/data
      - /scratchNVM0/ndhuynh/endure-torch:/endure
    ports:
      - "8888:8888"
