[project]
name = "proj_axe"
version = "0.1"
requires-python = "~=3.10"
dependencies = [
    "dill",
    "joblib",
    "mlos",
    "mlos-core[smac]",
    "numba",
    "numpy",
    "pandas",
    "pandas-stubs",
    "polars",
    "pyarrow",
    "pydantic",
    "pytest",
    "reinmax",
    "scipy",
    "toml",
    "torch",
    "torchdata",
    "tqdm",
    "typer",
    "typing-extensions",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "basedpyright",
    "ruff",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["axe*"]

[project.scripts]
axe = "axe.cli:app"

[tool.basedpyright]
typeCheckingMode = "standard"

