[project]
name = "ENDURE"
log_level = "INFO"
data_dir = "/Users/ndhuynh/sandbox/data"
experiments = [
    #'Exp01',
    'CostSurfaceExp']

[system]
B = 4           # Entries per page
phi = 1         # Read/write asymmetry
s = 0.00        # Range query selectivity
E = 1024        # (Bytes) entry size
H = 10          # (bits) Budget bits per element 
N = 100000000   # Number elments

[exp_config]
    [exp_config.Exp01]
    wl_ids = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

[inputs]
    [[inputs.workloads]]
    id = 0
    z0 = 0.25
    z1 = 0.25
    q  = 0.25
    w  = 0.25

    [[inputs.workloads]]
    id = 1
    z0 = 0.97
    z1 = 0.01
    q = 0.01
    w = 0.01

    [[inputs.workloads]]
    id = 2
    z0 = 0.01
    z1 = 0.97
    q = 0.01
    w = 0.01

    [[inputs.workloads]]
    id = 3
    z0 = 0.01
    z1 = 0.01
    q = 0.97
    w = 0.01

    [[inputs.workloads]]
    id = 4
    z0 = 0.01
    z1 = 0.01
    q = 0.01
    w = 0.97

    [[inputs.workloads]]
    id = 5
    z0 = 0.49
    z1 = 0.49
    q = 0.01
    w = 0.01

    [[inputs.workloads]]
    id = 6
    z0 = 0.49
    z1 = 0.01
    q = 0.49
    w = 0.01

    [[inputs.workloads]]
    id = 7
    z0 = 0.49
    z1 = 0.01
    q = 0.01
    w = 0.49

    [[inputs.workloads]]
    id = 8
    z0 = 0.01
    z1 = 0.49
    q = 0.49
    w = 0.01

    [[inputs.workloads]]
    id = 9
    z0 = 0.01
    z1 = 0.49
    q = 0.01
    w = 0.49

    [[inputs.workloads]]
     id = 10
     z0 = 0.01
     z1 = 0.01
     q = 0.49
     w = 0.49

     [[inputs.workloads]]
     id = 11
     z0 = 0.33
     z1 = 0.33
     q = 0.33
     w = 0.01

     [[inputs.workloads]]
     id = 12
     z0 = 0.33
     z1 = 0.33
     q = 0.01
     w = 0.33

     [[inputs.workloads]]
     id = 13
     z0 = 0.33
     z1 = 0.01
     q = 0.33
     w = 0.33

     [[inputs.workloads]]
     id = 14
     z0 = 0.01
     z1 = 0.33
     q = 0.33
     w = 0.33
