model = "KCostModel"
log_level = "INFO"
early_stop_num = 2

[io]
data_dir = "/scratchNVM0/ndhuynh/data"
train_dir = "cost_k_feather"
train_data = [
    "k_wl_0.feather",
    "k_wl_1.feather",
    "k_wl_2.feather",
    # "k_wl_3.feather",
    "k_wl_4.feather",
    "k_wl_5.feather",
    "k_wl_6.feather",
    "k_wl_7.feather",
    "k_wl_8.feather",
    "k_wl_9.feather",
    "k_wl_10.feather",
    "k_wl_11.feather",
    "k_wl_12.feather",
    "k_wl_13.feather",
    "k_wl_14.feather",
]
test_data = ["k_wl_3.feather"]

[static_params]
max_levels = 16
max_size_ratio = 50
# h, z0, z1, q, w
mean_bias = [6.45, 0.500, 0.500, 0.500, 0.500]
std_bias = [2.49,  3.464, 3.464, 3.464, 3.464]

[hyper_params]
num_cont_vars = 5
num_cate_vars = 17
hidden_layers = 2
embedding_size = 17

[train]
max_epochs = 128
train_batch_size = 32
val_batch_size = 8192
validate_frac = 0.1
learning_rate = 0.001
lr_schedule_gamma = 0.9
