model = "KCostModel"

[log]
level = "INFO"
name = "endure"

[io]
data_dir = "/data"
train_dir = "train_data"
test_dir = "test_data"
model_dir = "models"

[static_params]
max_levels = 16
max_size_ratio = 50
# h, z0, z1, q, w
mean_bias = [4.75, 0.5, 0.5, 0.5, 0.5]
std_bias =  [2.74,  0.3, 0.3, 0.3, 0.3]
out_dims = 4

[hyper_params]
num_cont_vars = 5
num_cate_vars = 17
hidden_layers = 2
embedding_size = 17

[train]
max_epochs = 128
batch_size = 1024
learning_rate = 0.001
# If training is via SGD, this will be the gamma decay parameter for learning
learning_rate_decay = 0.9
early_stop_num = 2
shuffle = true

[validate]
batch_size = 16384
percent = 0.1
shuffle = false
