model = "KCostModel"
log_level = "INFO"
early_stop_num = 2

[io]
data_dir = "/scratchNVM0/ndhuynh/data"
train_dir = "training_data"
train_data = [
    "train_0.feather",
    "train_1.feather",
    "train_2.feather",
    # "train_3.feather",
    # "train_4.feather",
    # "train_5.feather",
    # "train_6.feather",
    # "train_7.feather",
    # "train_8.feather",
    # "train_9.feather",
    # # "train_10.feather",
    # "train_11.feather",
    # "train_12.feather",
    # "train_13.feather",
    # "train_14.feather",
    # "train_15.feather",
    # "train_16.feather",
    # "train_17.feather",
    # "train_18.feather",
]
test_data = ["train_19.feather"]

[static_params]
max_levels = 16
max_size_ratio = 50
# h, z0, z1, q, w
mean_bias = [4.75, 0.5, 0.5, 0.5, 0.5]
std_bias =  [2.74,  0.3, 0.3, 0.3, 0.3]

[hyper_params]
num_cont_vars = 5
num_cate_vars = 17
hidden_layers = 2
embedding_size = 17

[train]
max_epochs = 128
train_batch_size = 32
val_batch_size = 8192
validate_frac = 0.1
learning_rate = 0.001
lr_schedule_gamma = 0.9
