# =============================================================================
# HEADER LCMDataGen
#   Settings for data generation job
# =============================================================================

# Directory to save all parquet data files
dir = "/data/test-data/kcost-t30"

# Each file will contain the following prefix
#   e.g. <file_prefix>_0000.parquet
file_prefix = "kcost"

# Generator dictates which LSM design to generate data for
#   Classic - Generates both leveling and tiering items
#   Tiering
#   Leveling
#   QFixed
#   KHybrid
generator = "KHybrid"

# Parallel workers, -1 issues all cores to be used
num_workers = -1

# Number of total files to generate
num_files = 2

# Number of samples per file
samples = 1024

# If we generate a file and see a conflicting file in the directory, we can
# either overwrite or skip creating the file all together
overwrite_if_exists = true

# =============================================================================
# HEADER LOG
#   Bounds for data creation
# =============================================================================
[log]
name = 'endure-logger'
format = "[%(levelname)s][%(asctime)-15s][%(filename)s] %(message)s"
datefmt = '%d-%m-%y:%H:%M:%S'
level = "DEBUG"
disable_tqdm = false

# =============================================================================
# HEADER BOUNDS
#   Bounds for data creation
# =============================================================================
[bounds]
max_levels = 20                             # Max number of levels to consider
size_ratio_range = [2, 31]                  # low, high of size ratios to consider
page_sizes = [4, 8, 16]                     # KB pages
entry_sizes = [1024, 2048, 4096, 8192]      # bits
memory_budget_range = [5, 20]               # low, high, bits per element
selectivity_range = [1e-7, 1e-9]            # low, high
elements_range = [100000000, 1000000000]    # element range

